backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

#  branch: master
media_folder: 'static/images'
public_folder: '/images'
publish_mode: editorial_workflow
local_backend: true

collections:
  - name: 'Pages'
    label: 'Pages'
    extension: mdx
    format: frontmatter
    media_folder: ''
    public_folder: ''
    create: true
    files:
      - label: 'About Page'
        name: 'About'
        file: 'content/pages/about/index.mdx'
        fields:
          - {label: 'title', name: 'title', widget: 'string'}
          - {label: 'slug', name: 'slug', required: true, pattern: [ '^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters' ], widget: 'string' }
          - {label: 'Cover Image', name: 'cover', widget: 'image' }
          - { label: 'Blog post content', name: 'body', widget: 'markdown' }

      - label: 'Instagram Page'
        name: 'instagram'
        file: 'content/pages/instagram/index.mdx'
        fields:
          - { label: 'title', name: 'title', widget: 'string' }
          - { label: 'slug', name: 'slug', required: true, pattern: [ '^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters' ], widget: 'string' }
          - {label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }
          - { label: 'Custom', name: 'custom', widget: 'boolean' }
          - { label: 'Cover Image', name: 'cover', widget: 'image' }
          - { label: 'Blog post content', name: 'body', widget: 'markdown' }


  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    path: '{{slug}}/index'
    extension: mdx
    format: frontmatter
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - {label: 'title', name: 'title', widget: 'string' }
      - {label: 'shortTitle', name: 'shortTitle', widget: 'string' }
      - {label: 'slug', name: 'slug', required: true, pattern: [ '^[a-z0-9]+(?:-[a-z0-9]+)*$','A slug can have no spaces or special characters' ]  }
      - {label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }
      - {label: 'Category', name: 'category', widget: 'select', options: ["trend", "still", "simple"], default: 'still' }
      - {label: 'Cover Image', name: 'cover', widget: 'image' }
      - {label: 'date', name: 'date', widget: 'datetime', default: '', format: 'DD-MM-YYYY'  }
      - { label: 'Blog post content', name: 'body', widget: 'markdown' }


